chatServerAPP/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace chatServerAPP.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    // public IActionResult Error()
    // {
    //     return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    // }
}

chatServerAPP/Controllers/RatingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using chatServer.Models;
using Services.Rating;

namespace chatServerAPP.Controllers;

public class RatingController : Controller
{
    // private readonly chatServerContext _context;
    private static IRatingService _service = new RatingService();



    // GET: Rating
    public async Task<IActionResult> Index()
    {
        ViewBag.average = _service.AverageStars();
        return _service.GetAll() != null ? 
            View( _service.GetAll()) :
            Problem("Entity set 'chatServerContext.Rating'  is null.");
    }

    // GET: Rating/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null )
        {
            return NotFound();
        }

        var rating =  _service.GetAll().Find(m => m.Id == id);
        if (rating == null)
        {
            return NotFound();
        }

        return View(rating);
    }

    // GET: Rating/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Rating/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name,Review,Stars")] Rating rating)
    {
        // if (ModelState.IsValid) // need to check why its not work
        // {
        _service.Add(rating.Stars, rating.Name, rating.Review);
        return RedirectToAction(nameof(Index));
        // }
        // return View(rating); // return to the same page
    }

    // GET: Rating/Edit/5
    public async Task<IActionResult> Edit(int id)
    {
        if (id == null || _service.GetAll() == null)
        {
            return NotFound();
        }

        var rating =  _service.Get(id);
        if (rating == null)
        {
            return NotFound();
        }
        return View(rating);
    }

    // POST: Rating/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Review,Time,Stars")] Rating rating)
    {
        if (id != rating.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _service.Update(rating);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RatingExists(rating.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(rating);
    }

    // GET: Rating/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _service.GetAll() == null)
        {
            return NotFound();
        }

        var rating =  _service.GetAll()
            .Find(m => m.Id == id);
        if (rating == null)
        {
            return NotFound();
        }

        return View(rating);
    }

    // POST: Rating/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_service.GetAll() == null)
        {
            return Problem("Entity set 'chatServerContext.Rating'  is null.");
        }
        var rating =  _service.Get(id);
        if (rating != null)
        {
            _service.Delete(rating.Id);
        }
            
        return RedirectToAction(nameof(Index));
    }

    private bool RatingExists(int id)
    {
        return (_service.GetAll()?.Any(e => e.Id == id)).GetValueOrDefault();
    }


    public  async Task<IActionResult> Search(string search)
    {
        List<Rating> list = _service.GetAll();
        return View(nameof(search), list.Where(x=> x.Name.ToLower().Contains(search.ToLower())));
    }
 
}

chatServerAPP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

chatServerAPP/Views/Rating/Create.cshtml
@model chatServer.Models.Rating

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Rating</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Review" class="control-label"></label>
                <input asp-for="Review" class="form-control" />
                <span asp-validation-for="Review" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stars" class="control-label"></label>
                <input asp-for="Stars" class="form-control" />
                <span asp-validation-for="Stars" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary mt-1 mb-1" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

chatServerAPP/Views/Rating/Delete.cshtml
@model chatServer.Models.Rating

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rating</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Review)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Review)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stars)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stars)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

chatServerAPP/Views/Rating/Details.cshtml
@model chatServer.Models.Rating

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Rating</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Review)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Review)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stars)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stars)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

chatServerAPP/Views/Rating/Edit.cshtml
@model chatServer.Models.Rating

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Rating</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Review" class="control-label"></label>
                <input asp-for="Review" class="form-control" />
                <span asp-validation-for="Review" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stars" class="control-label"></label>
                <input asp-for="Stars" class="form-control" />
                <span asp-validation-for="Stars" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary  mt-1 mb-1" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

chatServerAPP/Views/Rating/Search.cshtml
@model IEnumerable<chatServer.Models.Rating>

@{
    ViewData["Title"] = "search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stars)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in @Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stars) /5
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<div>
        <a asp-action="Index">Back to List</a>
</div>

chatServerAPP/Views/Rating/index.cshtml
@model IEnumerable<chatServer.Models.Rating>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="m-4 ">
    <div class="row">
        <h1 class="col-5 col">The Rating Page</h1>
        <form asp-action="Search" asp-controller="Rating" asp-route-search="search" class="col-5">
            <div class="form-group d-flex col">
                <input id="search" name="search" class="form-control w-100" placeholder="Search Rating"/>
                <button type="submit" class="btn btn-primary m-2"> Search </button>
            </div>
        </form>

    </div>
    <p>
        the average is @ViewBag.average stars
    </p>

    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Review)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stars)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stars) / 5
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <p>
        <a asp-action="Create">Create New</a>
    </p>

</div>

chatServerAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - chatServerAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Layout.css" asp-append-version="true"/>

</head>
<body>

<div class=" mainPage">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container text-white">
        &copy; whatAppChat Peleg & Nadav 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>